-- Read-only catalog extraction used for ATD-108 Q6. Run only as a metadata query.
with scoped as (select c.* from pg_class c join pg_namespace n on n.oid=c.relnamespace where (n.nspname,c.relname) in (('arowana','entities'),('arowana','financial_accounts'),('public','ai_briefs'),('public','ap_founders_waitlist'),('public','ap_risk_settings'),('public','ap_roll_coach'),('public','ap_usage'),('public','app_config'),('public','arowana_tools'),('public','arowana_webhooks'),('public','business_profiles'),('public','cc_candidates'),('public','csp_candidates'),('public','daily_setups'),('public','entities'),('public','finance_transactions'),('public','financial_accounts'),('public','journal_trades'),('public','market_snapshots'),('public','option_chains'),('public','option_roll_chains'),('public','profiles'),('public','tj_options'),('public','tj_stocks'),('public','trading_journal'),('public','user_api_keys'),('public','user_cash_balances'),('public','user_deployment_plans'),('public','user_preferences'),('public','v_finance_month_summary_all'),('public','v_finance_top_categories_month_all'),('public','watchlist_items'),('public','watchlists')))
select jsonb_build_object(
'columns',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',a.attname,'position',a.attnum,'type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'identity',a.attidentity,'generated',a.attgenerated,'default',pg_get_expr(d.adbin,d.adrelid),'collation',case when a.attcollation<>t.typcollation then a.attcollation::regcollation::text end) order by n.nspname,c.relname,a.attnum) from scoped c join pg_namespace n on n.oid=c.relnamespace join pg_attribute a on a.attrelid=c.oid and a.attnum>0 and not a.attisdropped join pg_type t on t.oid=a.atttypid left join pg_attrdef d on d.adrelid=c.oid and d.adnum=a.attnum),
'constraints',(select jsonb_agg(jsonb_build_object('table',conrelid::regclass::text,'name',conname,'type',contype,'definition',pg_get_constraintdef(oid,true),'reference',case when confrelid<>0 then confrelid::regclass::text end) order by conrelid::regclass::text,conname) from pg_constraint where conrelid in (select oid from scoped)),
'indexes',(select jsonb_agg(jsonb_build_object('table',i.indrelid::regclass::text,'name',i.indexrelid::regclass::text,'definition',pg_get_indexdef(i.indexrelid),'constraint_backed',exists(select 1 from pg_constraint k where k.conindid=i.indexrelid)) order by i.indexrelid::regclass::text) from pg_index i where i.indrelid in(select oid from scoped)),
'policies',(select jsonb_agg(to_jsonb(p) order by schemaname,tablename,policyname) from pg_policies p where (schemaname,tablename) in (('arowana','entities'),('arowana','financial_accounts'),('public','ai_briefs'),('public','ap_founders_waitlist'),('public','ap_risk_settings'),('public','ap_roll_coach'),('public','ap_usage'),('public','app_config'),('public','arowana_tools'),('public','arowana_webhooks'),('public','business_profiles'),('public','cc_candidates'),('public','csp_candidates'),('public','daily_setups'),('public','entities'),('public','finance_transactions'),('public','financial_accounts'),('public','journal_trades'),('public','market_snapshots'),('public','option_chains'),('public','option_roll_chains'),('public','profiles'),('public','tj_options'),('public','tj_stocks'),('public','trading_journal'),('public','user_api_keys'),('public','user_cash_balances'),('public','user_deployment_plans'),('public','user_preferences'),('public','v_finance_month_summary_all'),('public','v_finance_top_categories_month_all'),('public','watchlist_items'),('public','watchlists'))),
'views',(select jsonb_agg(jsonb_build_object('name',c.oid::regclass::text,'definition',pg_get_viewdef(c.oid,true),'options',c.reloptions) order by c.oid::regclass::text) from scoped c where relkind='v'),
'triggers',(select jsonb_agg(jsonb_build_object('table',tgrelid::regclass::text,'name',tgname,'definition',pg_get_triggerdef(oid,true),'function',tgfoid::regprocedure::text,'enabled',tgenabled) order by tgrelid::regclass::text,tgname) from pg_trigger where tgrelid in(select oid from scoped) and not tgisinternal),
'grants',(select jsonb_agg(to_jsonb(g) order by table_schema,table_name,grantee,privilege_type) from information_schema.table_privileges g where (table_schema,table_name) in (('arowana','entities'),('arowana','financial_accounts'),('public','ai_briefs'),('public','ap_founders_waitlist'),('public','ap_risk_settings'),('public','ap_roll_coach'),('public','ap_usage'),('public','app_config'),('public','arowana_tools'),('public','arowana_webhooks'),('public','business_profiles'),('public','cc_candidates'),('public','csp_candidates'),('public','daily_setups'),('public','entities'),('public','finance_transactions'),('public','financial_accounts'),('public','journal_trades'),('public','market_snapshots'),('public','option_chains'),('public','option_roll_chains'),('public','profiles'),('public','tj_options'),('public','tj_stocks'),('public','trading_journal'),('public','user_api_keys'),('public','user_cash_balances'),('public','user_deployment_plans'),('public','user_preferences'),('public','v_finance_month_summary_all'),('public','v_finance_top_categories_month_all'),('public','watchlist_items'),('public','watchlists'))),
'column_grants',(select jsonb_agg(to_jsonb(g) order by table_schema,table_name,column_name,grantee,privilege_type) from information_schema.column_privileges g where (table_schema,table_name) in (('arowana','entities'),('arowana','financial_accounts'),('public','ai_briefs'),('public','ap_founders_waitlist'),('public','ap_risk_settings'),('public','ap_roll_coach'),('public','ap_usage'),('public','app_config'),('public','arowana_tools'),('public','arowana_webhooks'),('public','business_profiles'),('public','cc_candidates'),('public','csp_candidates'),('public','daily_setups'),('public','entities'),('public','finance_transactions'),('public','financial_accounts'),('public','journal_trades'),('public','market_snapshots'),('public','option_chains'),('public','option_roll_chains'),('public','profiles'),('public','tj_options'),('public','tj_stocks'),('public','trading_journal'),('public','user_api_keys'),('public','user_cash_balances'),('public','user_deployment_plans'),('public','user_preferences'),('public','v_finance_month_summary_all'),('public','v_finance_top_categories_month_all'),('public','watchlist_items'),('public','watchlists'))),
'view_dependencies',(select jsonb_agg(distinct jsonb_build_object('view',v.oid::regclass::text,'dependency',d.refobjid::regclass::text)) from scoped v join pg_rewrite r on r.ev_class=v.oid join pg_depend d on d.classid='pg_rewrite'::regclass and d.objid=r.oid and d.refclassid='pg_class'::regclass and d.refobjid<>v.oid where v.relkind='v'),
'functions',(select jsonb_agg(jsonb_build_object('name',p.oid::regprocedure::text,'schema',n.nspname,'definition',pg_get_functiondef(p.oid),'owner',pg_get_userbyid(p.proowner),'acl',p.proacl) order by p.oid::regprocedure::text) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','arowana') and (p.proname like 'ap_%' or p.oid in(select tgfoid from pg_trigger where tgrelid in(select oid from scoped) and not tgisinternal) or p.oid in(select d.refobjid from pg_depend d join pg_policy pol on d.classid='pg_policy'::regclass and pol.oid=d.objid where pol.polrelid in(select oid from scoped) and d.refclassid='pg_proc'::regclass)))
) as snapshot;
